trigger:
  - main
  - develop

pr:
  - main
  - develop

variables:
  isMainBranch: $[eq(variables['Build.SourceBranchName'], 'main')]
  isTestBuildBranch: $[eq(variables['Build.SourceBranchName'], 'f-add_package_build_and_deploy')]

pool:
  vmImage: 'windows-2019'

jobs:

  - job: BuildAndDeploy
#    dependsOn: RunTests
    condition: eq(variables.isTestBuildBranch, 'True')
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Install or update pip.'

    - script: |
        python -m pip install build wheel twine
      displayName: 'Install build, wheel and twine tools.'

    - script: python -m build --wheel
      displayName: 'Build stable python wheel from package source.'

    - script: |
        python -m twine upload --username "__token__" --password '$(TWINE_TOKEN)' --verbose --repository testpypi dist/*
      displayName: 'Upload stable python wheel to test public pypi'